apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  template:
    spec:
      containers:
      - name: datadog-agent

        env:
        - name: DD_CRI_SOCKET_PATH
          value: "/run/containerd/containerd.sock"

        volumeMounts:
        - name: runtimesocket
          mountPath: /run/containerd/containerd.sock

      volumes:
      - hostPath:
          path: /run/containerd/containerd.sock
        name: runtimesocket
