- op: test
  path: '/spec/template/spec/containers/0/args/4'
  value: --publish-service=$(POD_NAMESPACE)/$(SERVICE_NAME)
- op: replace
  path: '/spec/template/spec/containers/0/args/4'
  value: --publish-status-address=10.69.4.66

- op: add
  path: '/spec/template/spec/containers/0/args/6'
  value: --ingress-class=wg69
