---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automaton
spec:
  template:
    spec:
      containers:
      - name: app

        args:
        - --unhandled-rejections=strict
        - automaton
        - --app
        - irc
        - --default-mounts
        - --/irc-modem
        - skylink+http://irc-modem
        - --/coinbase-api
        - skylink+http://coinbase-api-client
