---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automaton
spec:
  template:
    spec:
      containers:
      - name: app

        args:
        - automaton
        - --app
        - irc
        - --/source
        - file://routines/irc
        - --/irc-modem
        - skylink+http://irc-modem
        - --/config
        - session://config/irc
        - --/persist
        - session://persist/irc
        - --/state
        - temp://
