---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dustjs-backend-firebase
spec:
  template:
    spec:
      containers:
      - name: app

        env:
        - name: DUSTJS_SCHEMA_PATH
          value: builtin-schemas/:/opt/skychat/api-schemas/

        volumeMounts:
        - name: api-schemas
          mountPath: /opt/skychat/api-schemas

      volumes:
      - name: api-schemas
        configMap:
          name: api-schemas
