apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: starnotify

resources:
- ../../apps/starnotify
- ../../apps/stardriver-irc-client

patches:
- path: deployment-env.yaml
  target:
    kind: Deployment
# deployments get deleted whenever
- path: preemptible-pods.yaml
  target:
    kind: Deployment
# statefulsets stay running
- path: persistent-pods.yaml
  target:
    kind: StatefulSet

secretGenerator:
- env: credentials.env
  name: credentials

images:
- name: gcr.io/stardust-156404/multi-starnotify
  newTag: h6
