---
apiVersion: v1
kind: Service
metadata:
  name: firebase-server
spec:
  type: ClusterIP
  selector:
    app: firebase-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9239

---
apiVersion: v1
kind: Service
metadata:
  name: firebase-direct
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: firebase-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9239
