apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../apps/reggie
patchesStrategicMerge:
- node-assignment.yaml

configMapGenerator:
- name: reggie-config
  files:
  - config.yml
