apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../apps/lambdabot

configMapGenerator:
- name: lambdabot-config
  files:
  - lambdabot=lambdabot.rc

images:
- name: gcr.io/stardust-156404/lambdabot
  newTag: full
