namespace: nagios
commonLabels:
  app: nagios

resources:
- statefulset.yaml
- service.yaml

configMapGenerator:

- name: httpd-conf
  files:
  - nagios.conf=httpd-conf/nagios.conf
  - php.conf=httpd-conf/php.conf

images:
- name: nagios
  newName: gcr.io/stardust-156404/nagios
  newTag: h2
