apiVersion: batch/v1
kind: Job
metadata:
  name: push-meteor-buildenv
  labels:
    purpose: build
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: docker
        image: gcr.io/stardust-156404/build-shell
        securityContext:
          privileged: true
        args:
        - bash
        - -exc
        - |
          export DOCKER_HOST=
          dockerd --host=unix:///var/run/docker.sock &
          cd $(mktemp -d)

          cat >Dockerfile <<EOF
            FROM node:8-buster
            RUN apt update \
             && apt install -y curl build-essential python git bash \
             && rm -rf /var/lib/apt/lists/*
            RUN curl https://install.meteor.com/ | sh
          EOF
          Image="gcr.io/stardust-156404/meteor-buildenv"
          docker build -t "$Image" .
          docker push "$Image"

          kubectl delete job push-meteor-buildenv

      nodeSelector:
        purpose: build
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
