namespace: nagios

bases:
- ../../apps/nagios

resources:
- auth-proxy.yaml
- letsencrypt.yaml

patches:

- path: preemptible-pods.yaml
  target:
    kind: StatefulSet
- path: wireguard-sidecar.yaml
  target:
    kind: StatefulSet

secretGenerator:

- name: nagios-oauth
  env: auth-proxy.env

- name: wireguard-key
  env: wireguard.env

configMapGenerator:

- name: nagios-auth-config
  files:
  - email_list.txt
  - oauth2_proxy.cfg

- name: wireguard-conf
  files:
  - wg0.conf=wireguard.conf
