---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drone-server
spec:
  serviceName: drone-server

  replicas: 1
  updateStrategy:
    type: RollingUpdate

  template:
    spec:
      containers:

      - name: app
        image: drone/drone:1
        ports:
        - name: http
          containerPort: 80

        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 1000m
            memory: 50Mi

        volumeMounts:
        - name: data
          mountPath: /data

        envFrom:
        - secretRef:
            name: drone-server-env
        - secretRef:
            name: drone-rpc-env

      # don't care about preemptible status
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Exists
        effect: NoSchedule

      # https://discourse.drone.io/t/drone-server-changing-ports-protocol/4144
      enableServiceLinks: false

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
