---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multi-sqs
  labels:
    starnotify: multi-sqs
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        starnotify: multi-sqs
    spec:
      containers:
      - name: starnotify
        image: gcr.io/stardust-156404/multi-starnotify
        args:
        - 'node'
        - 'src/_host'
        env:
        - name: SQS_QUEUE_URL_BASE
          value: https://sqs.us-west-2.amazonaws.com/414064234042/

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    starnotify: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        starnotify: jenkins
    spec:
      containers:
      - name: starnotify
        image: gcr.io/stardust-156404/multi-starnotify
        args:
        - 'node'
        - 'src/jenkins'
