apiVersion: apps/v1
kind: Deployment
metadata:
  name: dust-poc
spec:
  template:
    spec:

      containers:
      - name: app
        env:

        - name: AWS_REGION
          value: us-west-2

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: AWS_SECRET_ACCESS_KEY
