---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dust-poc-int
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "600"
    kubernetes.io/ingress.class: wg69
spec:
  rules:

  - host: dustbox.wg69.net
    http:
      paths:
      - path: /
        backend:
          serviceName: dust-poc
          servicePort: 80
