namespace: dust-poc

bases:
- ../../apps/dust-poc
resources:
- namespace.yaml
- ingress.yaml

patchesStrategicMerge:
- deployment-patch.yaml

secretGenerator:
- env: aws-credential.env # TODO: eventually becomes 'envs: - ...'
  name: aws-credential

images:
- name: gcr.io/stardust-156404/dust-poc
  newName: gcr.io/stardust-156404/dust-poc-kubectl
  newTag: a543f57
