---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skychat-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: skychat-logic
        args:
        - api
        ports:
        - name: http
          containerPort: 9231

        resources:
          requests:
            cpu: 25m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 500Mi

        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 60

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /run/secret/firebase-adminsdk-key.json

        volumeMounts:
        - name: secrets
          mountPath: /run/secret

      # don't care about preemptible status
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Exists
        effect: NoSchedule
