namespace: skychat

images:

- name: dustjs-automaton-lua
  newName: gcr.io/stardust-156404/dustjs-automaton-lua
  newTag: 'f7df7f9'

- name: stardriver-irc-modem
  newName: gcr.io/stardust-156404/irc-modem
  newTag: h20

- name: stardriver-coinbase-api-client
  newName: gcr.io/stardust-156404/coinbase-api-client
  newTag: h4

bases:
# - api
- ../../apps/stardriver-coinbase-api-client # for !btc
- irc-modem
# - ../../apps/bitlbee

# human users
- automatons/dan-irc
- automatons/nat-irc
# chatbots
- automatons/skyhook-irc

resources:
- namespace.yaml
# - api-ingress.yaml
# - api-ingress-wg69.yaml

# patchesJson6902:
# - path: integrations-env-patch.yaml
#   target:
#     kind: StatefulSet
