namespace: dust-domain

bases:
- ../../apps/firebase-server
resources:
- namespace.yaml
- ingress.yaml
- letsencrypt.yaml

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
- name: firebase-server-configs
  files:
  - devmodecloud.json=config.json

secretGenerator:
- name: firebase-server-credentials
  files:
  - devmodecloud.json=credential.json
