---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automaton
spec:
  serviceName: skychat-automaton

  replicas: 1
  updateStrategy:
    type: RollingUpdate

  volumeClaimTemplates: []
  template:
    spec:
      containers:

      - name: app
        image: skychat-logic
        args:
        - automaton
        ports:
        - name: http
          containerPort: 9232

        envFrom:
        - secretRef:
            name: automaton-env

        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 75Mi

      # don't care about preemptible status
      tolerations:
      - key: cloud.google.com/gke-preemptible
        operator: Exists
        effect: NoSchedule
