namespace: wg69

bases:
- ../../apps/conduit-api-server

resources:
- namespace.yaml
- ingress.yaml
- letsencrypt.yaml

- wg-proxy.yaml
- wg-proxy-services.yaml

patchesStrategicMerge:
- conduit-gcloud-patch.yaml

secretGenerator:
- name: conduit-gcloud-key
  files:
  - key.json=conduit-gcloud-key.json

- name: wg-proxy-key
  envs:
  - wg-proxy.env

configMapGenerator:
- name: wg-proxy-conf
  files:
  - wg0.conf=wg-proxy.conf

images:
- name: conduit-api-server
  newName: gcr.io/stardust-156404/conduit-api-server
  newTag: 59f2a58
